STANDARD_NETSUITE_OBJECTS_MAP = {
    "Account": "Account",
    "Accounting Book": "accountingBook",
    "Accounting Context": "AccountingContext",
    "Accounting Period": "accountingPeriod",
    "Account Type": "accountType",
    "Address": "Address",
    "Address Book": "transactionReturnAddressbook",
    "Approval Status": "timeLineApprovalStatus",
    "Automated Clearing House": "AutomatedClearingHouse",
    "Billing Class": "BillingClass",
    "Budget": "budgets",
    "Budget Exchange Rate": "budgetExchangeRate",
    "Buying Reason": "buyingReason",
    "Buying Time Frame": "buyingTimeFrame",
    "Cardholder Authentication": "cardholderAuthentication",
    "Class": "classification",
    "Competitor": "Competitor",
    "Consolidated Exchange Rate": "consolidatedExchangeRate",
    "Contact": "Contact",
    "Contact Category": "ContactCategory",
    "Contact Role": "ContactRole",
    "Country": "Country",
    "Currency": "currency",
    "Customer": "Customer",
    "Customer Category": "customerCategory",
    "Customer Message": "customerMessage",
    "Customer-Subsidiary Relationship": "CustomerSubsidiaryRelationship",
    "Department": "department",
    "Domain": "domain",
    "Edition": "edition",
    "Email Preference Type": "EmailPreferenceType",
    "Email Template": "EmailTemplate",
    "Employee": "employee",
    "Employee Expense Source Type": "EmployeeExpenseSourceType",
    "Employee Status": "EmployeeStatus",
    "Employee Type": "EmployeeType",
    "Employee Type Category": "EmployeeTypeCategory",
    "Entity": "entity",
    "Entity Status": "EntityStatus",
    "Entity Type": "EntityType", # TODO: not supported in Nesuite catalog
    "Entry Form": "Entryformtemplate", # TODO: not supported in Nesuite catalog
    "Ethnicity": "Ethnicity", # TODO: not supported in Nesuite catalog
    "Event": "BaseEvent", # TODO: not supported in Nesuite catalog
    "Event Priority": "EventPriority",
    "Expense Category": "ExpenseCategory",
    "Field": "SystemNoteField",
    "Field Type": "scriptFieldType",
    "Financial Institution": "financialInstitution", # TODO: not supported in Nesuite catalog
    "Format Profile": "formatProfile",
    "General Token": "generalToken",
    "Imported Employee Expense": "ImportedEmployeeExpense",
    "Imported Employee Expense Status": "ImportedEmployeeExpenseStatus",
    "Incoterm": "Incoterm",
    "Item": "item",
    "Item Collection": "ItemCollection",
    "Item Location Configuration": "itemLocationConfiguration", # TODO: not supported in Nesuite catalog
    "Item Type": "PresItemType",
    "Locale": "Locale", # TODO: not supported in Nesuite catalog
    "Location": "Location",
    "Location Type": "LocationType",
    "Marital Status": "MaritalStatus", # TODO: not supported in Nesuite catalog
    "Negative Number Format": "NegativeNumberFormat",
    "News Item": "NewsItem", # TODO: not supported in Nesuite catalog
    "Nexus": "Nexus",
    "Note Type": "NoteType",
    "Number Format": "NumberFormat",
    "Opportunity": "opportunity", # TODO: not supported in Nesuite catalog
    "Order Status": "SalesOrderStatus", # TODO: not supported in Nesuite catalog
    "Originating Lead": "OriginatingLead", # TODO: not supported in Nesuite catalog
    "Other Name Category": "otherNameCategory",
    "Partner": "Partner",
    "Payment Card": "paymentCard",
    "Payment Card Token": "paymentCardToken",
    "Payment Instrument": "paymentInstrument",
    "Payment Method": "paymentMethod",
    "Payment Processing Profile": "PaymentProcessingProfile",
    "Price Level": "priceLevel",
    "Pricing Group": "pricingGroup",
    "Profile Type": "FormatProfileType", # TODO: not supported in Nesuite catalog
    "Project": "job",
    "Project Type": "JobType",
    "Prompt": "Prompt",
    "Quantity Pricing Schedule": "QuantityPricingSchedule",
    "Recommendation Blocklist": "RecSysBlocklist",
    "Recommendation Scenario": "RecSysScenario",
    "Record Type": "ScriptRecordType",
    "Resident Status": "ResidentStatus", # TODO: not supported in Nesuite catalog
    "Role": "role",
    "Sales Readiness": "salesReadiness",
    "Sales Territory": "salesTerritory",
    "Saved Search": "savedsearch", # TODO: not supported in Nesuite catalog
    "Script": "script",
    "Script Deployment": "scriptDeployment",
    "Shipping Partner Registration": "ShippingPartnerRegistration",
    "State": "State",
    "Subsidiary": "Subsidiary",
    "Subsidiary Settings": "SubsidiarySettings",
    "Task": "Task",
    "Tax Code": "salesTaxItem",
    "Tax Period": "taxPeriod", # TODO: not supported in Nesuite catalog
    "Tax Type": "taxType",
    "Text Enhance Action": "TextEnhanceAction",
    "Transaction": "transaction",
    "Transaction Form": "Formtemplate", # TODO: not supported in Nesuite catalog
    "Transaction Status": "TaxLiabilityPaymentStatus", # TODO: not supported in Nesuite catalog
    "Transaction Type": "CustomFieldTranType", # TODO: not supported in Nesuite catalog
    "Vendor": "Vendor",
    "Vendor Category": "VendorCategory",
    "Vendor-Subsidiary Relationship": "VendorSubsidiaryRelationship",
    "Visa Type": "VisaType", # TODO: not supported in Nesuite catalog
    "Win/Loss Reason": "winLossReason",
    "Work Calendar": "workCalendar", # TODO: not supported in Nesuite catalog
    "Workplace": "workplace" # TODO: not supported in Nesuite catalog
}

STANDARD_NETSUITE_OBJECTS_SELECT_MAP = {
    "Account": "id, displaynamewithhierarchy as name",
    "Accounting Period": "id, periodname as name",
    "Account Type": "id, longname as name",
    "Address Book": "internalid as id, label as name",
    "Approval Status": "key as id, name",
    "Consolidated Exchange Rate": "id, averagerate as name",
    "Contact": "id, fullname as name",
    "Customer": "id, fullname as name",
    "Domain": "id, domain as name",
    "Employee": "id, entityid as name",
    "Employee Type Category": "key as id, name",
    "Entity": "id, fullname as name",
    "Entity Status": "key as id, name",
    "Field": "key as id, label as name",
    "Format Profile": "id, formatprofile as name",
    "Imported Employee Expense": "id, memo as name",
    "Imported Employee Expense Status": "id, description as name",
    "Item": "id, displayname as name",
    "Item Type": "id, itemtype as name",
    "Location": "id, fullname as name",
    "Negative Number Format": "key as id, name",
    "Number Format": "key as id, name",
    "Nexus": "id, description as name",
    "Partner": "id, fullname as name",
    "Payment Card": "id, nameOnCard as name",
    "Payment Card Token": "id, cardNameOnCard as name",
    "Payment Instrument": "id, memo as name",
    "Project": "id, fullName as name",
    "Record Type": "internalId as id, name",
    "Script Deployment": "id, title as name",
    "State": "id, fullname as name",
    "Subsidiary Settings": "id, subsidiary as name",
    "Task": "id, title as name",
    "Transaction": "id, title as name",
    "Vendor": "id, fullname as name",
}
